### ISSUE TITLE
RISC-V: Output explict -mno-div

### ISSUE THREAD

**Issue by JohannesSpecht** [eclipse-embed-cdt/eclipse-plugins#323]
### Description
_Properties_ --> _C/C++ Build_ --> _Settings_ --> _Tool Settings_ --> _Target Processor_, the combination (_Architecture_ = _RV32I_, _Multiply Extension (RVM)_ = _YES_, and _Integer Divide Instructions (-mdiv)_ = _NO_) causes linkage of newlib-nano libraries that require divide/modulo instructions.

### Steps to Reproduce

1. Compile a "Hello World" program that prints an integer variable (i.e., `printf("%d", some_integer_variable);`)
2. Disassemble the binary
3. Open the assembler code

**Expected behaviour:** 
No divide/modulo instructions found in the assembler code.

**Actual behaviour:**
Divide/modulo instructions found in the assembler code.

### Versions

* plug-in version: 4.4.2.201809300
* Eclipse version: 2018-09 (4.9.0) 20180917-1800
* toolchain version: 7.2.0-4-20180606-1631

**Comment by ilg-ul** [comment]
sorry, but I cannot follow you.

where is the bug in the plug-ins? does the plug-in call the compiler with wrong command line options?

**Comment by ilg-ul** [comment]
So, if I understand you right, the plug-in should always use on of the `-mdiv`/`-mno-div`, and do not rely on the default, right?

In this case the same may happen to the other boolean options, which, when the interface was designed, assumed the `no-*` variant to be the default.

Tommy, what do you think? (@TM1234)

**Comment by JohannesSpecht** [comment]
**Right:** This is my suggestion, because the GCC default (https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html) for `-mdiv`/`-mno-div` is the opposite of what was assumed when the interface was designed, if I understand you correctly. Being explicit in both cases appears reasonable to me from a maintainers perspective.

**Comment by TM1234** [comment]
I'm not sure that I understand this either.

> Properties --> C/C++ Build --> Settings --> Tool Settings --> Target Processor, the combination (Architecture = RV32I, Multiply Extension (RVM) = YES, and Integer Divide Instructions (-mdiv) = NO) causes linkage of newlib-nano libraries that require divide/modulo instructions.

I presume that YES and NO here mean checkbox checked and unchecked respectively?

> The plug-in switch Integer divide instructions (-mdiv) is not effective in presence of the M extension (-march=rv32im): By default, GCC implicitly assumes -mdiv if the M extension is present. It is required to set -mno-div to effectively disable divide instructions in presence of the M extension (cmp. https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html).

Bear in mind that the RISC-V plugin does allow incompatible options to be specified as far as I recall - e.g. an incoompatible abi for the selected arch. My recollection is that since these are caught by the underlying tools Liviu decided not to do exhaustive configuration option cross checking in the GUI.

Having said that are you suggesting that perhaps the GUI should present both the "yes" (e.g. -mdiv) and "no" (e.g. -mno-div) options in the GUI to be used in different situations?

BTW I'm also confused what multilib would be selected in this case:

-march=rv32imaf -mabi=ilp32f -mno-div

Since as far as I know the multilibs are arranged by arch/abi only.
Or does the build process provide multilibs for, say...

-march=rv32imaf/-mabi=ilp32f aka -march=rv32imaf/-mabi=ilp32f/-mdiv
-march=rv32imaf/-mabi=ilp32f/-mno-div

and also for all other similar options - e.g. -mfdiv/-,no-fdiv etc.?

**Comment by TM1234** [comment]
> Or does the build process provide multilibs for, say...
> 
> -march=rv32imaf/-mabi=ilp32f aka -march=rv32imaf/-mabi=ilp32f/-mdiv
> -march=rv32imaf/-mabi=ilp32f/-mno-div

As far as I can see the way that the multilibs to be built are specified does not allow for this:

https://github.com/gcc-mirror/gcc/blob/master/gcc/config/riscv/t-elf-multilib
https://github.com/gcc-mirror/gcc/blob/master/gcc/config/riscv/multilib-generator

Am I missing/misunderstanding something here?

**Comment by ilg-ul** [comment]
I think we have two issues here.

Tommy correctly identified the multilibs issue; the settings for most of these extra options must match the options used when building the libraries, it makes no sense to build the main program with `-mno-div` and link it with a library built with `-mdiv`. Probably the same for `-mfdiv` and others.

The second issue is the GUI behaviour.

The initial design assumed that the `no-*` versions are the defaults, but Johannes carefully read the manual page and discovered that this is not true; not specifying `-mdiv` or `-mno-div` at all defaults to `-mdiv` for architectures with the 'M' extension, and to `-mno-div` for architectures without the 'M' extension.

The proposal is to always generate `-mno-div` for projects with this button not checked (the `-mdiv` is generated when the button is cheked, as it is now).

A slightly incompatible version would be to transform the option from a binary button to a drop down control, with yes/now/default values.

**Comment by TM1234** [comment]
Thanks Liviu - I get it now.

> The proposal is to always generate -mno-div for projects with this button not checked (the -mdiv is generated when the button is cheked, as it is now).

That seems to make sense alright. 

But it seems moot until/unless the multilib issue is also resolved and at the moment I don't see that the multilib-generator script and the parameter format that it takes is capable of generating separate multilibs for, say...

march=rv32im/abi=ilp32 [implicitly -mdiv]
march=rv32im/abi=ilp32/-mno-div

And I don't know if gcc (or ld?) has the smarts to select the appropriate multilib based on the parameters passed?

Ditto for some or all of the other options (in particular the -m[no-]option options) here:

https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html

On the other hand perhaps the idea is that the user will build the tools with the appropriate multilib[s] and then just make sure to use the appropriate one rather than depending on the tools to infer the appropriate one from the flags passed in?

Probably needs a separate issue for the multilib issue but I don't think that that is a GME issue?

**Comment by ilg-ul** [comment]
>> always generate -mno-div

> That seems to make sense alright.

assuming the compiler does not complain about them if the M extension is not present

same for the other options.

the multilib issue is a toolchain issue, and I don't know how to address it.

**Comment by ilg-ul** [comment]
I also sent a message to @palmer-dabbelt, perhaps he can suggest a better approach.

**Comment by JohannesSpecht** [comment]
**@ilg-ul On the yes/no/default drop-down for HW divide**
Sounds good. Let me just recommend to let the tooltip explicitly say something like "If you choose default, please look into the GCC docs" - the defaults are not obvious.

**On -mabi, -march, -mno-div/-div, multilib toolchain, etc.**
I'm concerned that support for all _valid_ combinations of GCC RISC-V architecture knobs (= _profiles_) for all valid ABIs (x) may not be possible in the multilib toolchain, at least short term. 
However, I also see good reasons to support `-march` - related partial implementations of the M extension (i.e., compared to HW multiply, HW divide is tougher in several aspects). There may be good reasons for partial support of other extensions as well. Those who brought the `-mdiv`/`-mno-div` knobs into GCC may have had similar motivations, but I don't know the details on this ... 
(x): The _set_ of valid ABIs should (just) be a function of an architecture profile. The underlying toolchain may check this for consistency. 

As said in my 2nd comment, I'd also love to see pre-compiled libs for _all_ valid architecture profiles (with at least one valid ABI per architecture profile). But right now, pre-compiled libs for all architecture profiles are not present. There are pre-compiled libs for _some_ `-march` strings. 
W.r.t. the plug-in mechanics, this becomes a problem: If a plug-in user selects to _not_ use HW divide in presence of the M extension (which implies HW multiplication is still there), the _wrong_ pre-compiled libs are automatically _linked_. Namely, the `rv32im` libs, as build by the present multilib toolchain. The result is a binary that likely won't run properly on the target processor. And that's one of these hard-to-find cases (took some time to find out what's wrong...). I hope we can take this burden from other users.

**@ilg-ul On "..., and I don't know how to address it"**
It seems ther are some alternatives:

1. The first (short term) solution is stated in my 2nd comment. I hope it can be done quickly in the plug-in. That is, if HW dividers are disabled and the M extension is selected, _link_ with the pre-compiled libs for `rv32i`, _not_ those for `rv32im`. In general, this approach ("if there is only a subset of a particular extension present, take the libs for the `-march` setting without the extension") may be applicable to other GCC knobs. 
Sure, such an approach is sub-optimal because the linked libs use SW multiply only, although HW multiply is supported by the target processor. Well, at least the user code can still be _compiled_ with HW multiply enabled... And the approach seems solid (e.g., several OS distributions do so). Plus, which appears to be the most important aspect, users get a binary that works on their target processor.

2. A second alternative short term solution would be to remove the `-mdiv` knob entirely from the plug-in. But I don't like this one. As stated, `-mdiv`/`-mno-div` makes totally sense from a HW designers perspective, especially for small processors. This option is great - please keep such options in your plug-in in an accessible manner.

3. A third alternative solution is to do your own multilib build scripts, maybe in the riscv-none-gcc project. I don't know whether this is possible or desirable. It is not an GME issue then, sure, but given that (a) project riscv-none-gcc has the github issue tracker disabled and (b) you are contributing to project riscv-none-gcc, I feel no guilt to comment here - I hope you can take the necessary steps. Project riscv-none-gcc already seems to do more than the original RISC-V release from SiFive Inc. and, according to the README of project riscv-none-gcc (section Changes) it reads to me that there is room for more architecture profiles.

**@TM1234 On the idea that the user will build the tools with the appropriate multilib[s]**
Sorry, I may not get your comment right (???): 
- If you mean that the plug-in automatically builds the libraries for the chosen architecture profile from source if required/not yet there, then this could work. Although there may be several caveats. 
- If you mean that the user builds the libs via console or so, well ... I believe the majority of Eclipse plug-in users neither want to build the libs (=tools?) by hand, especially if the existing build scripts have limitations, nor are they aware that they have to pay special attention on the GCC docs, the mechanics of the existing multilib build scripts, etc. to avoid strange compile results.

**Comment by ilg-ul** [comment]
> That is, if HW dividers are disabled and the M extension is selected, link with the pre-compiled libs for rv32i, not those for rv32im. In general, this approach ("if there is only a subset of a particular extension present, take the libs for the -march setting without the extension") may be applicable to other GCC knobs.

too complicated

>  remove the -mdiv knob entirely from the plug-in. But I don't like this one. As stated, -mdiv/-mno-div makes totally sense from a HW designers perspective, especially for small processors. This option is great - please keep such options in your plug-in in an accessible manner.

you always have the misc field where you can add any options you need

> A third alternative solution is to do your own multilib build scripts, 

building the RISC-V toolchain binaries already takes almost one day; adding more multilibs will make this even longer.

but I doubt that the linker is able to differentiate libraries based on anything else than -march/-mabi, so such custom libraries will need to be packed as separate distributions.

given that SiFive no longer supports GME development, further work on the RISC-V related plug-ins and toolchains will be kept to a minimum (basically bug fixes).

so, if you want to build your own toolchain, feel free to do it, the build script is quite configurable.

as for the GUI knobs, I'd still prefer to remove `-mplt -mfdiv -mdiv` completely; I don't know about `-msave-restore`.

**Comment by JohannesSpecht** [comment]
> 
> 
> > That is, if HW dividers are disabled and the M extension is selected, link with the pre-compiled libs for rv32i, not those for rv32im. In general, this approach ("if there is only a subset of a particular extension present, take the libs for the -march setting without the extension") may be applicable to other GCC knobs.
> 
> too complicated

It's a pity to read this verdict.

> 
> > remove the -mdiv knob entirely from the plug-in. But I don't like this one. As stated, -mdiv/-mno-div makes totally sense from a HW designers perspective, especially for small processors. This option is great - please keep such options in your plug-in in an accessible manner.
> 
> you always have the misc field where you can add any options you need

... beside what I already said about the value of the architecture checkboxes, the misc field would run into the same linking issues that motivated me to report this issue. If the checkboxes disappear, you even cannot place warnings about lib linking issues (e.g., in checkbox tooltips).

> 
> > A third alternative solution is to do your own multilib build scripts,
> 
> building the RISC-V toolchain binaries already takes almost one day; adding more multilibs will make this even longer.

I was not aware of this. Would this be a practical problem? I mean - are frequent builds required?

> 
> but I doubt that the linker is able to differentiate libraries based on anything else than -march/-mabi, so such custom libraries will need to be packed as separate distributions.

Indeed, this seems to be very right, although it might be seen as an argument for the first proposed solution.

> 
> given that SiFive no longer supports GME development, further work on the RISC-V related plug-ins and toolchains will be kept to a minimum (basically bug fixes).
> 

Too bad to hear this. I'm writing here as an individual, doing RISC-V in spare time. Unfortunately I cannot help the GME project in this respect, nor am I familar enough with the Eclipse infrastructure to quickly contribute a pull request by myself - sorry. No community momentum/interest from other vendors?

> as for the GUI knobs, I'd still prefer to remove `-mplt -mfdiv -mdiv` completely; I don't know about `-msave-restore`.

See above. I believe GME will loose a lot of value for RISC-V. The plug-in did an excellent job for me since I installed it, thank you! I hope development can move forward.

**Comment by TM1234** [comment]
> **@TM1234 On the idea that the user will build the tools with the appropriate multilib[s]**
> Sorry, I may not get your comment right (???):
> 
> * If you mean that the plug-in automatically builds the libraries for the chosen architecture profile from source if required/not yet there, then this could work. Although there may be several caveats.
> * If you mean that the user builds the libs via console or so, well ... I believe the majority of Eclipse plug-in users neither want to build the libs (=tools?) by hand, especially if the existing build scripts have limitations, nor are they aware that they have to pay special attention on the GCC docs, the mechanics of the existing multilib build scripts, etc. to avoid strange compile results.

I meant the latter.
More and more it seems to be that it's almost impossible to have build a toolchain that meets every user's requirements - I thought that just building all arch/abi multilibs would go most of the way towards this but now that the -m[no-]option options are considered this further complicates matters. Building a single toolchain with all possible arch/abi x all relevant -m[no-]option options (a) is currently not possible (b) will probably be complicated and require changes to how the tools find the "appropriate" lib based on the arch/abi and other options and (c) will result in a toolchain that is huge because it's further bloated by an increasing number of multilibs. 

At the moment my feeling is that the plugins should just present all relevant options (the GUI presenting the "commonly used" ones and others can be input manually into "other" options fields) and let the underlying tools do what they do. I don't think that the plugins can easily try to validate all options to ensure that they are valid to the underlying tools or result in a successful compilation. In short I think that the user needs to know what they're doing and the plugins can't spoon feed them too much.

> As said in my 2nd comment, I'd also love to see pre-compiled libs for all valid architecture profiles (with at least one valid ABI per architecture profile). 

I'm not clear on what you mean by "profiles" here.
Do you mean arch/abi tuples multiplied by all relevant -m[no-]option options?
At the moment the multilib-generator script and the arguments that it takes to create the t-elf-multilib file cannot cater for the -m[no-]option options as far as I can see.

We [Microchip/Microsemi] already use a modified version of Liviu's build scripts to build multilibs for all archs and their "native/natural" abi. This results in 39 sets of multilibs c. 1.25GB in size. Multiplying by the all combinations of -m[no-]option options would explode this further.

**Comment by TM1234** [comment]
FWIW I've posted to the mailing list about the multilib issue:

https://groups.google.com/a/groups.riscv.org/forum/#!topic/sw-dev/CCttfcRD9gw

**Comment by TM1234** [comment]
@ilg-ul - just curious - do you know if/how the Arm plugin and toolchain deal with this issue or does it arise at all there...? Perhaps not if the architecture configuration options are more constrained than in RISC-V?

**Comment by TM1234** [comment]
> I agree that probably nobody want's to download a Blue-ray disk full of all combinations (which multiplies by factor two for every new [binary] knob in GCC).

Just to be pedantic I don;'t think that every -m[no-]option multiplies ALL libs by two since they may not apply to all arch/abis - e.g. -m[no-]div only applies to M arch/abi tuples and not non M ones.

> The proposed "fallback" (my first proposal) to the pre-compiled libs with the next lower available `-march` setting during _linking_ (which I believe would work...) would not have this problem.

But would that work for ALL -m[no-]option options and other architectural options here:

https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html

In at least some cases (e.g. -mpreferred-stack-boundary=num) the client code AND library code must be compiled with the same option. I don't know if this also applies to others in the doc above?

> Note that, on the technical level, I do not think that I'm talking about heavy-weight multi-parameter validations. Or do I miss something here?

Sorry - I introduced that because it is related but not something that you raised.

**Comment by ilg-ul** [comment]
> do you know if/how the Arm plugin and toolchain deal with this issue

the arm plug-in dose nothing of this sort.

as for the toolchain, I know that there are lots of settings for the mcu, and lots of different libraries, but I did not study the details on how the linker selects the libraries.

**Comment by TM1234** [comment]
What about all of the Arm options here?

https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

I just wondered if, like at least the RISC-V -mpreferred-stack-boundary=num option, these applied to both the code being compiled AND any libs/objs linked in?

I had a quick look at the Arm toolchain but it seems to arrange multilibs for different architectures (and other options?) differently to the RISC-V toolchain.

**Comment by ilg-ul** [comment]
I don't know how the Arm multilib builds are configured, with so many options it might be possible to mess things, but in practical terms I never had this problem.

**Comment by TM1234** [comment]
OK - thanks.
