### ISSUE TITLE
Generate "source" features that constains "source" bundles 

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-embed-cdt/eclipse-plugins#397]
Our p2 repository should contain sources for all the bundles. I think this is one of requirements to join SimRel but I cannot find it to reference here.
At least that's what all good Eclipse citizens do.

**Comment by ilg-ul** [comment]
Agreed.

**Comment by ilg-ul** [comment]
Fixed in 2020-08-01 by Alexander.

**Comment by ilg-ul** [comment]
Alexander, what is the purpose of the source packages? Only to provide the source files for the Java classes when debugging?

Because I checked some source .jar files, and they only include the ilg.gnumcueclipse.* folders, and some minimal metadata.

All other files were skipped. When I check in Eclipse the `build.properties` file, the Binary Build lists has most files selected, but the Source Build section has no files selected at all. Is this ok?

**Comment by ruspl-afed** [comment]
> Alexander, what is the purpose of the source packages

I think the preimary reason is compliance with EPL-2.0, but also other benefits like source navigation that you already mentioned.

> 3. REQUIREMENTS
> 
> 3.1 If a Contributor Distributes the Program in any form, then:
> 
>     a) the Program must also be made available as Source Code

As for the content of the source build I plan to revisit all the bundles as a part of #402

**Comment by ilg-ul** [comment]
Ok, great.

Please note that the SiFive template project has some git submodules, with the code used to create RISC-V projects.
